In [79]:
import pandas as pd
import numpy as np
import requests

In [80]:
url = "https://api.pbpstats.com/get-totals/nba"
params = {
    "Season": "2025-26",
    "SeasonType": "Regular Season",
    "Type": "Team"
}
response = requests.get(url, params=params)
response_json = response.json()
league_totals = response_json["single_row_table_data"]

In [81]:
relative = pd.DataFrame([league_totals])

league_totals = pd.DataFrame([league_totals])
print(league_totals.columns.tolist())

['SecondsPlayed', 'GamesPlayed', 'OffPoss', 'DefPoss', 'PenaltyOffPoss', 'PenaltyDefPoss', 'SecondChanceOffPoss', 'TotalPoss', 'AtRimFGM', 'AtRimFGA', 'SecondChanceAtRimFGM', 'SecondChanceAtRimFGA', 'PenaltyAtRimFGM', 'PenaltyAtRimFGA', 'ShortMidRangeFGM', 'ShortMidRangeFGA', 'LongMidRangeFGM', 'LongMidRangeFGA', 'Corner3FGM', 'Corner3FGA', 'SecondChanceCorner3FGM', 'SecondChanceCorner3FGA', 'PenaltyCorner3FGM', 'PenaltyCorner3FGA', 'Arc3FGM', 'Arc3FGA', 'SecondChanceArc3FGM', 'SecondChanceArc3FGA', 'PenaltyArc3FGM', 'PenaltyArc3FGA', 'FG2M', 'FG2A', 'FG3M', 'FG3A', 'FtPoints', 'Points', 'OpponentPoints', 'SecondChanceFG2M', 'SecondChanceFG2A', 'SecondChanceFG3M', 'SecondChanceFG3A', 'SecondChanceFtPoints', 'SecondChancePoints', 'PenaltyFG2M', 'PenaltyFG2A', 'PenaltyFG3M', 'PenaltyFG3A', 'PenaltyFtPoints', 'PenaltyPoints', 'PtsAssisted2s', 'PtsUnassisted2s', 'PtsAssisted3s', 'PtsUnassisted3s', 'PtsPutbacks', 'NonHeaveArc3FGA', 'NonHeaveArc3FGM', 'Fg2aBlocked', 'Fg3aBlocked', 'TwoPtAssists', 'ThreePtAssists', 'Assists', 'Arc3Assists', 'Corner3Assists', 'AtRimAssists', 'ShortMidRangeAssists', 'LongMidRangeAssists', 'AssistPoints', 'OffThreePtRebounds', 'OffTwoPtRebounds', 'FTOffRebounds', 'DefThreePtRebounds', 'DefTwoPtRebounds', 'FTDefRebounds', 'DefRebounds', 'OffRebounds', 'Rebounds', 'SelfOReb', 'Steals', 'BadPassSteals', 'LostBallSteals', 'LiveBallTurnovers', 'BadPassOutOfBoundsTurnovers', 'BadPassTurnovers', 'DeadBallTurnovers', 'LostBallOutOfBoundsTurnovers', 'LostBallTurnovers', 'StepOutOfBoundsTurnovers', 'Travels', 'Turnovers', 'SecondChanceTurnovers', 'PenaltyTurnovers', 'ShootingFouls', 'Fouls', 'Charge Fouls', 'Clear Path Fouls', 'Loose Ball Fouls', 'Offensive Fouls', 'FoulsDrawn', 'Charge Fouls Drawn', 'Loose Ball Fouls Drawn', 'Offensive Fouls Drawn', 'FTA', '2pt And 1 Free Throw Trips', '3pt And 1 Free Throw Trips', 'Technical Free Throw Trips', 'TwoPtShootingFoulsDrawn', 'ThreePtShootingFoulsDrawn', 'NonShootingFoulsDrawn', 'Blocked2s', 'Blocked3s', 'BlockedArc3', 'BlockedAtRim', 'BlockedCorner3', 'BlockedLongMidRange', 'BlockedShortMidRange', 'Blocks', 'RecoveredBlocks', 'DefensiveGoaltends', 'OffensiveGoaltends', 'Defensive 3 Seconds Violations', 'FirstChancePoints', 'PenaltyPointsExcludingTakeFouls', 'PenaltyOffPossExcludingTakeFouls', 'NonShootingPenaltyNonTakeFouls', 'NonShootingPenaltyNonTakeFoulsDrawn', 'Assisted2sPct', 'NonPutbacksAssisted2sPct', 'Assisted3sPct', 'Fg3Pct', 'SecondChanceFg3Pct', 'PenaltyFg3Pct', 'NonHeaveFg3Pct', 'Fg2Pct', 'SecondChanceFg2Pct', 'PenaltyFg2Pct', 'EfgPct', 'SecondChanceEfgPct', 'PenaltyEfgPct', 'TsPct', 'SecondChanceTsPct', 'PenaltyTsPct', 'FG3APct', 'FG3APctBlocked', 'FG2APctBlocked', 'AtRimPctBlocked', 'ShortMidRangePctBlocked', 'LongMidRangePctBlocked', 'Corner3PctBlocked', 'Arc3PctBlocked', 'LiveBallTurnoverPct', 'DefFTReboundPct', 'OffFTReboundPct', 'DefTwoPtReboundPct', 'OffTwoPtReboundPct', 'DefThreePtReboundPct', 'OffThreePtReboundPct', 'DefFGReboundPct', 'OffFGReboundPct', 'OffAtRimReboundPct', 'OffShortMidRangeReboundPct', 'OffLongMidRangeReboundPct', 'OffArc3ReboundPct', 'OffCorner3ReboundPct', 'DefAtRimReboundPct', 'DefShortMidRangeReboundPct', 'DefLongMidRangeReboundPct', 'DefArc3ReboundPct', 'DefCorner3ReboundPct', 'SelfORebPct', 'Pace', 'BlocksRecoveredPct', 'SecondsPerPossOff', 'SecondsPerPossDef', 'SecondsExcludingORebsPerPossOff', 'SecondsExcludingORebsPerPossDef', 'AtRimFrequency', 'AtRimAccuracy', 'UnblockedAtRimAccuracy', 'AtRimPctAssisted', 'ShortMidRangeFrequency', 'ShortMidRangeAccuracy', 'UnblockedShortMidRangeAccuracy', 'ShortMidRangePctAssisted', 'LongMidRangeFrequency', 'LongMidRangeAccuracy', 'UnblockedLongMidRangeAccuracy', 'LongMidRangePctAssisted', 'Corner3Frequency', 'Corner3Accuracy', 'UnblockedCorner3Accuracy', 'Corner3PctAssisted', 'Arc3Frequency', 'Arc3Accuracy', 'UnblockedArc3Accuracy', 'Arc3PctAssisted', 'SecondChanceAtRimFrequency', 'SecondChanceAtRimAccuracy', 'SecondChanceAtRimPctAssisted', 'SecondChanceCorner3Frequency', 'SecondChanceCorner3Accuracy', 'SecondChanceCorner3PctAssisted', 'SecondChanceArc3Frequency', 'SecondChanceArc3Accuracy', 'SecondChanceArc3PctAssisted', 'PenaltyAtRimFrequency', 'PenaltyAtRimAccuracy', 'PenaltyCorner3Frequency', 'PenaltyCorner3Accuracy', 'PenaltyArc3Frequency', 'PenaltyArc3Accuracy', 'AtRimFG3AFrequency', 'NonHeaveArc3Accuracy', 'ShotQualityAvg', 'SecondChanceShotQualityAvg', 'PenaltyShotQualityAvg', 'ShootingFoulsDrawnPct', 'TwoPtShootingFoulsDrawnPct', 'ThreePtShootingFoulsDrawnPct', 'SecondChancePointsPct', 'PenaltyPointsPct', 'Avg2ptShotDistance', 'Avg3ptShotDistance', 'PenaltyOffPossPct']

In [82]:
league_totals = league_totals[["SecondChanceOffPoss", "SecondChancePoints", "OffRebounds", "Rebounds"]]

In [83]:
league_totals["orebpct"] = league_totals["OffRebounds"] / league_totals["Rebounds"]
league_totals["secondchanceppp"] = league_totals["SecondChancePoints"] / league_totals["SecondChanceOffPoss"]

In [84]:
league_totals

,SecondChanceOffPoss,SecondChancePoints,OffRebounds,Rebounds,orebpct,secondchanceppp
0,30096,36954,35463,121050,0.292962,1.227871

In [85]:
url = "https://api.pbpstats.com/get-totals/nba"
params = {
    "Season": "2025-26",
    "SeasonType": "Regular Season",
    "Type": "Player"
}
response = requests.get(url, params=params)
response_json = response.json()
player_stats = response_json["multi_row_table_data"]

In [86]:
player_stats_df = pd.DataFrame(player_stats)
player_stats_df

,EntityId,TeamId,Name,ShortName,RowId,TeamAbbreviation,SecondsPlayed,GamesPlayed,Minutes,PlusMinus,...,PeriodOTFouls5Minutes,FG3APctBlocked,Arc3PctBlocked,ThreePtShootingFoulsDrawnPct,Defensive 3 Seconds Violations,Period4Fouls5Minutes,Corner3PctBlocked,Clear Path Fouls,Period3Fouls5Minutes,Period1Fouls3Minutes
0,1641708,1610612745,Amen Thompson,Amen Thompson,1641708,HOU,177189.0,79,2953,368.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,201142,1610612745,Kevin Durant,Kevin Durant,201142,HOU,170389.4,78,2840,340.0,...,2.0,0.002222,0.002488,0.028200,NaN,NaN,NaN,NaN,NaN,NaN
2,1630217,1610612753,Desmond Bane,Desmond Bane,1630217,ORL,165362.7,82,2756,135.0,...,4.0,0.009324,0.008772,0.004651,1.0,34.0,0.011494,NaN,NaN,NaN
3,1641739,1610612757,Toumani Camara,Toumani Camara,1641739,POR,163874.2,82,2731,32.0,...,NaN,NaN,NaN,0.001686,NaN,45.0,NaN,NaN,NaN,NaN
4,1631095,1610612745,Jabari Smith Jr.,Jabari Smith Jr.,1631095,HOU,162321.9,77,2705,264.0,...,NaN,NaN,NaN,0.018109,NaN,10.0,NaN,1.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1641723,1610612747,Kobe Bufkin,Kobe Bufkin,1641723,LAL,7169.0,16,119,-68.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,200768,1610612755,Kyle Lowry,Kyle Lowry,200768,PHI,7082.4,14,118,-39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,1641726,1610612742,Dereck Lively II,Dereck Lively II,1641726,DAL,6916.4,7,115,14.0,...,NaN,NaN,NaN,NaN,1.0,4.0,NaN,NaN,NaN,NaN
498,1641725,1610612740,Trey Alexander,Trey Alexander,1641725,NOP,6638.6,9,111,-18.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,1631247,1610612739,Luke Travers,Luke Travers,1631247,CLE,6185.5,12,103,-32.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [87]:
print(player_stats_df.columns.tolist())

['EntityId', 'TeamId', 'Name', 'ShortName', 'RowId', 'TeamAbbreviation', 'SecondsPlayed', 'GamesPlayed', 'Minutes', 'PlusMinus', 'OffPoss', 'DefPoss', 'PenaltyOffPoss', 'PenaltyDefPoss', 'SecondChanceOffPoss', 'TotalPoss', 'AtRimFGM', 'AtRimFGA', 'SecondChanceAtRimFGM', 'SecondChanceAtRimFGA', 'PenaltyAtRimFGM', 'PenaltyAtRimFGA', 'ShortMidRangeFGM', 'ShortMidRangeFGA', 'LongMidRangeFGM', 'LongMidRangeFGA', 'Corner3FGM', 'Corner3FGA', 'SecondChanceCorner3FGM', 'SecondChanceCorner3FGA', 'PenaltyCorner3FGM', 'PenaltyCorner3FGA', 'Arc3FGM', 'Arc3FGA', 'SecondChanceArc3FGM', 'SecondChanceArc3FGA', 'PenaltyArc3FGM', 'PenaltyArc3FGA', 'FG2M', 'FG2A', 'FG3M', 'FG3A', 'FtPoints', 'Points', 'OpponentPoints', 'SecondChanceFG2M', 'SecondChanceFG2A', 'SecondChanceFG3M', 'SecondChanceFG3A', 'SecondChanceFtPoints', 'SecondChancePoints', 'PenaltyFG2M', 'PenaltyFG2A', 'PenaltyFG3M', 'PenaltyFG3A', 'PenaltyFtPoints', 'PenaltyPoints', 'PtsAssisted2s', 'PtsUnassisted2s', 'PtsAssisted3s', 'PtsUnassisted3s', 'PtsPutbacks', 'NonHeaveArc3FGA', 'NonHeaveArc3FGM', 'Fg2aBlocked', 'TwoPtAssists', 'ThreePtAssists', 'Assists', 'Arc3Assists', 'Corner3Assists', 'AtRimAssists', 'ShortMidRangeAssists', 'LongMidRangeAssists', 'AssistPoints', 'OffThreePtRebounds', 'OffTwoPtRebounds', 'FTOffRebounds', 'DefThreePtRebounds', 'DefTwoPtRebounds', 'FTDefRebounds', 'DefRebounds', 'OffRebounds', 'Rebounds', 'SelfOReb', 'Steals', 'BadPassSteals', 'LostBallSteals', 'LiveBallTurnovers', 'BadPassOutOfBoundsTurnovers', 'BadPassTurnovers', 'DeadBallTurnovers', 'LostBallOutOfBoundsTurnovers', 'LostBallTurnovers', 'StepOutOfBoundsTurnovers', 'Travels', 'Turnovers', 'SecondChanceTurnovers', 'PenaltyTurnovers', 'ShootingFouls', 'Fouls', 'Charge Fouls', 'Loose Ball Fouls', 'Offensive Fouls', 'FoulsDrawn', 'Charge Fouls Drawn', 'Loose Ball Fouls Drawn', 'Offensive Fouls Drawn', 'FTA', '2pt And 1 Free Throw Trips', 'TwoPtShootingFoulsDrawn', 'NonShootingFoulsDrawn', 'Blocked2s', 'Blocked3s', 'BlockedArc3', 'BlockedAtRim', 'BlockedCorner3', 'BlockedLongMidRange', 'BlockedShortMidRange', 'Blocks', 'RecoveredBlocks', 'DefensiveGoaltends', 'OffensiveGoaltends', 'FirstChancePoints', 'PenaltyPointsExcludingTakeFouls', 'PenaltyOffPossExcludingTakeFouls', 'NonShootingPenaltyNonTakeFouls', 'NonShootingPenaltyNonTakeFoulsDrawn', 'Period1Fouls2Minutes', 'Period2Fouls2Minutes', 'Period2Fouls3Minutes', 'Period2Fouls4Minutes', 'Period3Fouls3Minutes', 'Period3Fouls4Minutes', 'Period4Fouls4Minutes', 'PeriodOTFouls4Minutes', 'OnOffRtg', 'OnDefRtg', 'Assisted2sPct', 'NonPutbacksAssisted2sPct', 'Assisted3sPct', 'Fg3Pct', 'SecondChanceFg3Pct', 'PenaltyFg3Pct', 'NonHeaveFg3Pct', 'Fg2Pct', 'SecondChanceFg2Pct', 'PenaltyFg2Pct', 'EfgPct', 'SecondChanceEfgPct', 'PenaltyEfgPct', 'TsPct', 'SecondChanceTsPct', 'PenaltyTsPct', 'FG3APct', 'FG2APctBlocked', 'AtRimPctBlocked', 'ShortMidRangePctBlocked', 'LongMidRangePctBlocked', 'Usage', 'LiveBallTurnoverPct', 'DefFTReboundPct', 'OffFTReboundPct', 'DefTwoPtReboundPct', 'OffTwoPtReboundPct', 'DefThreePtReboundPct', 'OffThreePtReboundPct', 'DefFGReboundPct', 'OffFGReboundPct', 'OffAtRimReboundPct', 'OffShortMidRangeReboundPct', 'OffLongMidRangeReboundPct', 'OffArc3ReboundPct', 'OffCorner3ReboundPct', 'DefAtRimReboundPct', 'DefShortMidRangeReboundPct', 'DefLongMidRangeReboundPct', 'DefArc3ReboundPct', 'DefCorner3ReboundPct', 'SelfORebPct', 'BlocksRecoveredPct', 'AtRimFrequency', 'AtRimAccuracy', 'UnblockedAtRimAccuracy', 'AtRimPctAssisted', 'ShortMidRangeFrequency', 'ShortMidRangeAccuracy', 'UnblockedShortMidRangeAccuracy', 'ShortMidRangePctAssisted', 'LongMidRangeFrequency', 'LongMidRangeAccuracy', 'UnblockedLongMidRangeAccuracy', 'LongMidRangePctAssisted', 'Corner3Frequency', 'Corner3Accuracy', 'UnblockedCorner3Accuracy', 'Corner3PctAssisted', 'Arc3Frequency', 'Arc3Accuracy', 'UnblockedArc3Accuracy', 'Arc3PctAssisted', 'SecondChanceAtRimFrequency', 'SecondChanceAtRimAccuracy', 'SecondChanceAtRimPctAssisted', 'SecondChanceCorner3Frequency', 'SecondChanceCorner3Accuracy', 'SecondChanceCorner3PctAssisted', 'SecondChanceArc3Frequency', 'SecondChanceArc3Accuracy', 'SecondChanceArc3PctAssisted', 'PenaltyAtRimFrequency', 'PenaltyAtRimAccuracy', 'PenaltyCorner3Frequency', 'PenaltyCorner3Accuracy', 'PenaltyArc3Frequency', 'PenaltyArc3Accuracy', 'AtRimFG3AFrequency', 'NonHeaveArc3Accuracy', 'ShotQualityAvg', 'SecondChanceShotQualityAvg', 'PenaltyShotQualityAvg', 'ShootingFoulsDrawnPct', 'TwoPtShootingFoulsDrawnPct', 'SecondChancePointsPct', 'PenaltyPointsPct', 'Avg2ptShotDistance', 'Avg3ptShotDistance', 'AtRimOffReboundedPct', 'ShortMidRangeOffReboundedPct', 'LongMidRangeOffReboundedPct', 'ThreePtOffReboundedPct', 'PenaltyOffPossPct', 'Fg3aBlocked', '3pt And 1 Free Throw Trips', 'Technical Free Throw Trips', 'ThreePtShootingFoulsDrawn', 'PeriodOTFouls5Minutes', 'FG3APctBlocked', 'Arc3PctBlocked', 'ThreePtShootingFoulsDrawnPct', 'Defensive 3 Seconds Violations', 'Period4Fouls5Minutes', 'Corner3PctBlocked', 'Clear Path Fouls', 'Period3Fouls5Minutes', 'Period1Fouls3Minutes']

In [88]:
stats = player_stats_df[["Name", "GamesPlayed", "Usage", "Points", "Turnovers", "BadPassTurnovers", "BadPassOutOfBoundsTurnovers", "FG2A", "FG3A", "ThreePtShootingFoulsDrawn", "2pt And 1 Free Throw Trips", "3pt And 1 Free Throw Trips", "TwoPtShootingFoulsDrawn", "Technical Free Throw Trips", "FtPoints", "FTA", "FG2M", "FG3M", "OffPoss"]]
stats = stats.fillna(0)

In [89]:
stats["TrueFTPoss"] = (stats["TwoPtShootingFoulsDrawn"] - stats["2pt And 1 Free Throw Trips"]) + (stats["ThreePtShootingFoulsDrawn"] - stats["3pt And 1 Free Throw Trips"]) + ((stats["FTA"] - stats["Technical Free Throw Trips"] - stats["2pt And 1 Free Throw Trips"] - stats["3pt And 1 Free Throw Trips"]  - ((stats["TwoPtShootingFoulsDrawn"] - stats["2pt And 1 Free Throw Trips"]) * 2) - ((stats["ThreePtShootingFoulsDrawn"] - stats["3pt And 1 Free Throw Trips"]) * 3))*0.5)
relative["TrueFTPoss"] = (relative["TwoPtShootingFoulsDrawn"] - relative["2pt And 1 Free Throw Trips"]) + (relative["ThreePtShootingFoulsDrawn"] - relative["3pt And 1 Free Throw Trips"]) + ((relative["FTA"] - relative["Technical Free Throw Trips"] - relative["2pt And 1 Free Throw Trips"] - relative["3pt And 1 Free Throw Trips"]  - ((relative["TwoPtShootingFoulsDrawn"] - relative["2pt And 1 Free Throw Trips"]) * 2) - ((relative["ThreePtShootingFoulsDrawn"] - relative["3pt And 1 Free Throw Trips"]) * 3))*0.5)

In [90]:
stats["FTPercent"] = stats["FtPoints"] / stats["FTA"]
relative["FTPercent"] = relative["FtPoints"] / relative["FTA"]

In [91]:
stats["TruePoints"] = stats["Points"] - (stats["Technical Free Throw Trips"] * stats["FTPercent"])
relative["TruePoints"] = relative["Points"] - (relative["Technical Free Throw Trips"] * relative["FTPercent"])

In [92]:
stats["ScoringTurnovers"] = stats["Turnovers"] - (stats["BadPassTurnovers"] + stats["BadPassOutOfBoundsTurnovers"])
relative["ScoringTurnovers"] = relative["Turnovers"] - (relative["BadPassTurnovers"] + relative["BadPassOutOfBoundsTurnovers"])

In [93]:
stats["MissedFTOpportunities"] = (stats["TwoPtShootingFoulsDrawn"] + stats["ThreePtShootingFoulsDrawn"] + ((stats["FTA"] - stats["Technical Free Throw Trips"] - stats["2pt And 1 Free Throw Trips"] - stats["3pt And 1 Free Throw Trips"]  - ((stats["TwoPtShootingFoulsDrawn"] - stats["2pt And 1 Free Throw Trips"]) * 2) - ((stats["ThreePtShootingFoulsDrawn"] - stats["3pt And 1 Free Throw Trips"]) * 3))*0.5)) * (1 - stats["FTPercent"])
relative["MissedFTOpportunities"] = (relative["TwoPtShootingFoulsDrawn"] + relative["ThreePtShootingFoulsDrawn"] + ((relative["FTA"] - relative["Technical Free Throw Trips"] - relative["2pt And 1 Free Throw Trips"] - relative["3pt And 1 Free Throw Trips"]  - ((relative["TwoPtShootingFoulsDrawn"] - relative["2pt And 1 Free Throw Trips"]) * 2) - ((relative["ThreePtShootingFoulsDrawn"] - relative["3pt And 1 Free Throw Trips"]) * 3))*0.5)) * (1 - relative["FTPercent"])

In [94]:
stats["MissedShotsOpportunities"] = (stats["FG2A"] - stats["FG2M"]) + (stats["FG3A"] - stats["FG3M"]) + stats["MissedFTOpportunities"]
relative["MissedShotsOpportunities"] = (relative["FG2A"] - relative["FG2M"]) + (relative["FG3A"] - relative["FG3M"]) + relative["MissedFTOpportunities"]

In [95]:
league_totals

,SecondChanceOffPoss,SecondChancePoints,OffRebounds,Rebounds,orebpct,secondchanceppp
0,30096,36954,35463,121050,0.292962,1.227871

In [96]:
print(league_totals.dtypes)

SecondChanceOffPoss      int64
SecondChancePoints       int64
OffRebounds              int64
Rebounds                 int64
orebpct                float64
secondchanceppp        float64
dtype: object

In [97]:
stats["TS"] = 0.5 * (stats["TruePoints"] / (((stats["FG2A"] + stats["FG3A"] + stats["TrueFTPoss"]) * 1)))
league_totals
stats["PPP"] = 0.5 * ((stats["TruePoints"] + (stats["MissedShotsOpportunities"] * league_totals["orebpct"].item() * league_totals["secondchanceppp"].item() ) ) / (((stats["FG2A"] + stats["FG3A"] + stats["TrueFTPoss"]) * 1) + stats["ScoringTurnovers"]))
relative["PPP"] = 0.5 * ((relative["TruePoints"] + (relative["MissedShotsOpportunities"] * league_totals["orebpct"].item() * league_totals["secondchanceppp"].item() ) ) / (((relative["FG2A"] + relative["FG3A"] + relative["TrueFTPoss"])) + relative["ScoringTurnovers"]))

In [98]:
relative

,SecondsPlayed,GamesPlayed,OffPoss,DefPoss,PenaltyOffPoss,PenaltyDefPoss,SecondChanceOffPoss,TotalPoss,AtRimFGM,AtRimFGA,...,Avg2ptShotDistance,Avg3ptShotDistance,PenaltyOffPossPct,TrueFTPoss,FTPercent,TruePoints,ScoringTurnovers,MissedFTOpportunities,MissedShotsOpportunities,PPP
0,7121999.4,2460,245196,247046,61918,63426,30096,492242,41558,61788,...,6.294288,25.559403,0.252525,24925.0,0.782838,283543.054823,18854,6681.8499,123712.8499,0.62121

In [99]:
stats = stats.sort_values(by="Usage", ascending=False)
stats

,Name,GamesPlayed,Usage,Points,Turnovers,BadPassTurnovers,BadPassOutOfBoundsTurnovers,FG2A,FG3A,ThreePtShootingFoulsDrawn,...,FG3M,OffPoss,TrueFTPoss,FTPercent,TruePoints,ScoringTurnovers,MissedFTOpportunities,MissedShotsOpportunities,TS,PPP
36,Luka Dončić,64,37.342605,2143,255,138.0,31.0,763.0,694.0,19.0,...,254.0,4747,276.0,0.779845,2134.421705,86.0,74.852713,838.852713,0.615817,0.669646
269,Giannis Antetokounmpo,36,36.620312,993,115,26.0,6.0,553.0,45.0,0.0,...,15.0,2123,157.5,0.649860,993.000000,83.0,69.852941,294.852941,0.657181,0.655375
21,Jaylen Brown,71,35.616438,2038,259,54.0,23.0,1139.0,404.0,9.0,...,140.0,4905,227.5,0.794776,2030.052239,182.0,59.822761,866.822761,0.573299,0.599709
231,Joel Embiid,38,34.302117,1021,109,28.0,18.0,538.0,159.0,5.0,...,53.0,2481,150.5,0.853731,1018.438806,63.0,25.816418,381.816418,0.600849,0.634698
428,Ty Jerome,15,33.896104,295,27,6.0,2.0,115.0,100.0,1.0,...,42.0,684,20.5,0.875000,291.500000,19.0,3.812500,116.812500,0.618896,0.655245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,John Konchar,56,9.176641,248,35,23.0,4.0,100.0,99.0,0.0,...,28.0,2388,19.0,0.727273,248.000000,8.0,6.818182,111.818182,0.568807,0.637662
301,Dwight Powell,63,8.842593,210,41,8.0,10.0,94.0,7.0,0.0,...,2.0,1911,50.0,0.696429,210.000000,23.0,18.821429,54.821429,0.695364,0.660116
488,Bismack Biyombo,25,8.524590,23,8,1.0,1.0,15.0,0.0,0.0,...,0.0,280,3.0,0.714286,23.000000,6.0,1.142857,7.142857,0.638889,0.532696
351,Gary Harris,48,8.513514,128,19,8.0,2.0,36.0,68.0,0.0,...,28.0,1318,3.0,0.888889,128.000000,9.0,0.666667,58.666667,0.598131,0.642688
475,Mason Plumlee,20,7.710843,31,12,4.0,3.0,14.0,0.0,0.0,...,0.0,351,6.0,0.642857,31.000000,5.0,2.857143,5.857143,0.775000,0.662139

In [100]:
stats["PtsPer75"] = stats["Points"] / stats["OffPoss"] * 75
stats["TruePointsPer75"] = (stats["TruePoints"] + (stats["MissedShotsOpportunities"] * league_totals["orebpct"].item() * league_totals["secondchanceppp"].item())) / stats["OffPoss"] * 75
stats["ScoringTurnoversPer75"] = stats["ScoringTurnovers"] / stats["OffPoss"] * 75
stats["RelativeTSE"] = (stats["PPP"] - relative["PPP"].item()) * 100

In [101]:
stats = stats[["Name", "GamesPlayed", "Usage", "PtsPer75", "TruePointsPer75", "ScoringTurnoversPer75", "RelativeTSE", "PPP"]]

In [102]:
stats

,Name,GamesPlayed,Usage,PtsPer75,TruePointsPer75,ScoringTurnoversPer75,RelativeTSE,PPP
36,Luka Dončić,64,37.342605,33.858226,38.490198,1.358753,4.843610,0.669646
269,Giannis Antetokounmpo,36,36.620312,35.080075,38.827044,2.932171,3.416507,0.655375
21,Jaylen Brown,71,35.616438,31.162080,35.808331,2.782875,-2.150082,0.599709
231,Joel Embiid,38,34.302117,30.864571,34.939100,1.904474,1.348807,0.634698
428,Ty Jerome,15,33.896104,32.346491,36.570140,2.083333,3.403481,0.655245
...,...,...,...,...,...,...,...,...
259,John Konchar,56,9.176641,7.788945,9.052234,0.251256,1.645165,0.637662
301,Dwight Powell,63,8.842593,8.241758,9.015711,0.902669,3.890570,0.660116
488,Bismack Biyombo,25,8.524590,6.160714,6.848952,1.607143,-8.851385,0.532696
351,Gary Harris,48,8.513514,7.283763,8.484646,0.512140,2.147743,0.642688
475,Mason Plumlee,20,7.710843,6.623932,7.074129,1.068376,4.092839,0.662139

In [103]:
stats_table = stats.to_json(orient="records")

In [104]:
with open("../public/data.json", "w") as file:
    file.write(stats_table)

In [52]:
stats_30 = stats.head(30)
stats_30 = stats_30.sort_values(by="PPP", ascending=False)
stats_30

,Name,GamesPlayed,Usage,PtsPer75,TruePointsPer75,ScoringTurnoversPer75,RelativeTSE,PPP
44,Shai Gilgeous-Alexander,68,32.764505,33.503904,NaN,1.107829,8.242621,0.703636
42,Nikola Jokić,65,29.384501,28.185711,NaN,1.472739,6.915788,0.690368
207,Stephen Curry,43,31.463491,30.383115,NaN,1.516495,6.303155,0.684242
65,Kawhi Leonard,65,33.255169,32.702020,NaN,1.479076,5.245380,0.673664
36,Luka Dončić,64,37.342605,33.858226,NaN,1.358753,4.843610,0.669646
30,Donovan Mitchell,70,31.916039,29.847095,NaN,1.284404,4.115031,0.662360
22,James Harden,70,28.368412,25.136945,NaN,1.323798,3.883019,0.660040
59,Anthony Edwards,61,31.349754,29.532721,NaN,1.580009,3.565353,0.656864
269,Giannis Antetokounmpo,36,36.620312,35.080075,NaN,2.932171,3.416507,0.655375
428,Ty Jerome,15,33.896104,32.346491,NaN,2.083333,3.403481,0.655245
136,Michael Porter Jr.,52,29.853055,27.851459,NaN,1.547303,2.688937,0.648099
102,Victor Wembanyama,64,32.426920,30.864198,NaN,2.025463,2.677589,0.647986
14,Jalen Brunson,74,30.192435,27.565325,NaN,0.972726,2.335074,0.644561
7,Tyrese Maxey,70,29.065362,26.986364,NaN,1.131818,1.966369,0.640874
114,Keyonte George,54,27.951751,25.250858,NaN,1.881436,1.525000,0.636460
231,Joel Embiid,38,34.302117,30.864571,NaN,1.904474,1.348807,0.634698
54,Deni Avdija,66,29.052438,25.935945,NaN,1.996321,0.522221,0.626432
58,Devin Booker,64,31.297266,28.099730,NaN,1.752022,0.319341,0.624404
221,Coby White,50,29.121253,25.213013,NaN,2.120449,0.091873,0.622129
56,Cade Cunningham,64,30.146919,25.596300,NaN,1.487963,-1.005556,0.611155
69,Pascal Siakam,62,29.991766,25.817107,NaN,1.634214,-1.187125,0.609339
74,LaMelo Ball,72,31.262855,26.259995,NaN,1.617398,-1.647473,0.604735
21,Jaylen Brown,71,35.616438,31.162080,NaN,2.782875,-2.150082,0.599709
375,Jayson Tatum,16,29.684909,24.928367,NaN,1.575931,-2.187499,0.599335
132,Dillon Brooks,56,28.589201,24.235714,NaN,1.392857,-2.471231,0.596498
357,Anthony Davis,20,27.945205,23.553241,NaN,1.504630,-2.694066,0.594269
170,Shaedon Sharpe,50,29.880044,25.024015,NaN,1.945245,-2.920432,0.592006
306,Cam Thomas,42,30.250000,24.466859,NaN,1.772334,-3.922052,0.581990
364,Ja Morant,20,31.493277,23.758143,NaN,1.404723,-4.463294,0.576577
321,Jalen Green,32,31.720978,25.192194,NaN,2.084565,-5.361559,0.567595